/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.davipb.jamspell.jni;

public class JamSpellJNI {
  public final static native long new_StringVector__SWIG_0();
  public final static native long new_StringVector__SWIG_1(long jarg1);
  public final static native long StringVector_size(long jarg1, StringVector jarg1_);
  public final static native long StringVector_capacity(long jarg1, StringVector jarg1_);
  public final static native void StringVector_reserve(long jarg1, StringVector jarg1_, long jarg2);
  public final static native boolean StringVector_isEmpty(long jarg1, StringVector jarg1_);
  public final static native void StringVector_clear(long jarg1, StringVector jarg1_);
  public final static native void StringVector_add(long jarg1, StringVector jarg1_, String jarg2);
  public final static native String StringVector_get(long jarg1, StringVector jarg1_, int jarg2);
  public final static native void StringVector_set(long jarg1, StringVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_StringVector(long jarg1);
  public final static native boolean NativeSpellCorrector_loadLangModel(long jarg1, NativeSpellCorrector jarg1_, String jarg2);
  public final static native boolean NativeSpellCorrector_trainLangModel(long jarg1, NativeSpellCorrector jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long NativeSpellCorrector_getCandidates(long jarg1, NativeSpellCorrector jarg1_, long jarg2, StringVector jarg2_, long jarg3);
  public final static native String NativeSpellCorrector_fixFragment(long jarg1, NativeSpellCorrector jarg1_, String jarg2);
  public final static native String NativeSpellCorrector_fixFragmentNormalized(long jarg1, NativeSpellCorrector jarg1_, String jarg2);
  public final static native void NativeSpellCorrector_setPenalty(long jarg1, NativeSpellCorrector jarg1_, double jarg2, double jarg3);
  public final static native void NativeSpellCorrector_setMaxCandiatesToCheck(long jarg1, NativeSpellCorrector jarg1_, long jarg2);
  public final static native long new_NativeSpellCorrector();
  public final static native void delete_NativeSpellCorrector(long jarg1);
}
