/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.davipb.jamspell.jni;

public final class NativeSpellCorrector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public NativeSpellCorrector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(NativeSpellCorrector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JamSpellJNI.delete_NativeSpellCorrector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean loadLangModel(String modelFile) {
    return JamSpellJNI.NativeSpellCorrector_loadLangModel(swigCPtr, this, modelFile);
  }

  public boolean trainLangModel(String textFile, String alphabetFile, String modelFile) {
    return JamSpellJNI.NativeSpellCorrector_trainLangModel(swigCPtr, this, textFile, alphabetFile, modelFile);
  }

  public StringVector getCandidates(StringVector sentence, long position) {
    return new StringVector(JamSpellJNI.NativeSpellCorrector_getCandidates(swigCPtr, this, StringVector.getCPtr(sentence), sentence, position), true);
  }

  public String fixFragment(String text) {
    return JamSpellJNI.NativeSpellCorrector_fixFragment(swigCPtr, this, text);
  }

  public String fixFragmentNormalized(String text) {
    return JamSpellJNI.NativeSpellCorrector_fixFragmentNormalized(swigCPtr, this, text);
  }

  public void setPenalty(double knownWordsPenaly, double unknownWordsPenalty) {
    JamSpellJNI.NativeSpellCorrector_setPenalty(swigCPtr, this, knownWordsPenaly, unknownWordsPenalty);
  }

  public void setMaxCandiatesToCheck(long maxCandidatesToCheck) {
    JamSpellJNI.NativeSpellCorrector_setMaxCandiatesToCheck(swigCPtr, this, maxCandidatesToCheck);
  }

  public NativeSpellCorrector() {
    this(JamSpellJNI.new_NativeSpellCorrector(), true);
  }

}
